[BUGFIX] winston version fixing
[DESC.]
- winston v2.0 have a problem with webida-server

[REF log]

/home/webida/webida-server/webida.net/server/common/log-manager.js:65
            new (winston.transports.DailyRotateFile)({
            ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/webida/webida-server/webida.net/server/common/log-manager.js:65:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at svcType (/home/webida/webida-server/webida.net/server/unit-manager.js:78:14)
    at parseCommandLine (/home/webida/webida-server/webida.net/server/unit-manager.js:66:12)
    at Object.<anonymous> (/home/webida/webida-server/webida.net/server/unit-manager.js:70:1)
error: Forever detected script exited with code: 8